// src/pages/about.tsx
import { Box, Divider, Link, ListItem, Text, UnorderedList } from '@chakra-ui/react';
import Head from 'next/head';

import Card from '~/components/Card';
import CardBody from '~/components/Card/CardBody';
import CardHeader from '~/components/Card/CardHeader';
import Template from '~/components/Template';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sobre - CS Manager</title>
      </Head>
      <Template>
        <Card>
          <CardHeader title="Sobre" />
          <CardBody>
            <Box>
              <Text>Tecnologias Utilizadas:</Text>
              <UnorderedList mt="2">
                <ListItem>
                  <Link href="https://nextjs.org">Next.js</Link>
                </ListItem>
                <ListItem>
                  <Link href="https://www.typescriptlang.org">TypeScript</Link>
                </ListItem>
                <ListItem>
                  <Link href="https://chakra-ui.com">Chakra UI</Link>
                </ListItem>
                <ListItem>
                  <Link href="https://supabase.com">Supabase</Link>
                </ListItem>
              </UnorderedList>
            </Box>
            <Divider mt="-2" />
            <Box>
              <Text>Link do Projeto:</Text>
              <UnorderedList mt="2">
                <ListItem>
                  <Link href="https://github.com/JulianoBazzi/CSManager">GitHub</Link>
                </ListItem>
              </UnorderedList>
            </Box>
          </CardBody>
        </Card>
      </Template>
    </>
  );
}

// src/views/About.vue
<template>
  <div class="about">
    <Card title="Sobre">
      <p>Tecnologias Utilizadas:</p>
      <hr/>
      <ul>
        <li>
          <a href="https://vuejs.org/" target="_blank">Vue.js 2</a>
        </li>
        <li>
          <a href="https://vuex.vuejs.org/" target="_blank">Vuex</a>
        </li>
        <li>
          <a href="https://www.typescriptlang.org/" target="_blank">TypeScript</a>
        </li>
        <li>
          <a href="https://bootstrap-vue.org/" target="_blank">BootstrapVue</a>
        </li>
        <li>
          <a href="https://supabase.com/" target="_blank">Supabase</a>
        </li>
        <li>
          <a href="https://lodash.com/" target="_blank">Lodash</a>
        </li>
        <li>
          <a href="https://sweetalert2.github.io/" target="_blank">SweetAlert 2</a>
        </li>
      </ul>
      <hr/>
      <p>
        Link do Projeto:
        <a href="https://github.com/JulianoBazzi/CSManager" target="_blank">GitHub</a>
      </p>
    </Card>
  </div>
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';
import Card from '@/components/Card.vue';
import Base from '@/views/Base';

@Component({
  components: {
    Card,
  },
})
export default class About extends Base {
}
</script>
